### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by damiancastelao** [asierraperez/LMSXI-Boletin12-3enRaya#1]
¿Configuraste las pages para poder ver el tablero directamente en le navegador?
¿Cual es el enlace?

**Comment by asierraperez** [comment]
Se me olvido activar la web, ahora deberia funcionar 
https://asierraperez.github.io/LMSXI-Boletin12-3enRaya/

**Comment by damiancastelao** [comment]
Ahora ya puedes cerrar el Issue ;)

Damián Nogueiras Meléndez
....................................................................................................................
 CFP Daniel Castelao -  politica de privacidad click
<https://www.google.es/intl/es/policies/privacy/>
......................................................................................................................
